### ISSUE TITLE
Environment Setup

### ISSUE THREAD

**Issue by feipanir** [naver/relis#1]
Dear authors, thank you for sharing the code. Could you please give a detailed distribution on the environment setup? Like pytorch version, installing detectron2, Mask2Former, mmsegmentation, etc.

Thanks!

**Comment by pdejorge** [comment]
Dear @feipanir thank you for you interest. I have updated the README.md with more specific instructions regarding the installation and uploaded copies of our config files (two since we use a different one for mmsegmentation models and detectron2 models). I hope this helps with the installation!
